CREATE TABLE IF NOT EXISTS channeling.users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP(6) DEFAULT NULL,
  email VARCHAR(255) UNIQUE,
  fname VARCHAR(255) DEFAULT NULL,
  lname VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL

);
